import {
    defaultSecurityHeaders,
    defineConfig,
} from "@salesforce/storefront-next-runtime/config";
import type { Config } from "./src/types/config";
import { TrackingConsent } from "./src/types/tracking-consent";
// Auto-generated by `pnpm config:aggregate-extensions` from each extension's config.ts.
// Merging it into app.extension is what makes PUBLIC__app__extension__* env paths valid and
// reachable via useConfig() — without it those overrides are dropped as unknown config paths.
// The path is explicit to `config/index.ts`: a bare `./src/extensions/config` resolves to the
// sibling `config.json` extension registry, not this barrel. Relative (not the `@/` alias) —
// see the top-of-file note on vite-node/typegen.
import generatedExtensionConfig from "./src/extensions/config/index";
// Auto-generated by `pnpm config:aggregate-extensions` (same prestep that produces the
// client barrel above — the CLI runs both modes via Promise.all) from each extension's
// server-config.ts. Merged into app.serverExtension below; values are reachable via
// getConfig(context) on the server only. The client config extractor (src/lib/app-config-client.ts)
// strips serverExtension before window.__APP_CONFIG__, and a Vite plugin fails the build if
// any client chunk imports this barrel. There is intentionally no PUBLIC__ override path —
// the AST validator forbids process.env, so server-only secrets must be read from process.env
// in a route handler.
import generatedServerExtensionConfig from "./src/extensions/config/server";

const DIS_DEFAULT_HOST = "https://edge.disstg.commercecloud.salesforce.com";

export default defineConfig<Config>(
  {
    metadata: {
      projectName: "Storefront Next Retail App",
      projectSlug: "storefront-next-retail-app",
    },
    runtime: {
      defaultMrtProject: "",
      defaultMrtTarget: "",
      ssrOnly: [],
      ssrShared: [],
      ssrParameters: {
        ssrFunctionNodeVersion: "24.x",
        envBasePath: "",
      },
    },
    app: {
      pages: {
        navigation: {
          rootCategoryId: "root",
          maxDepth: 2,
        },
        home: {
          featuredProductsCount: 12,
        },
        cart: {
          quantityUpdateDebounce: 750,
          enableRemoveConfirmation: true,
          maxQuantityPerItem: 999,
          enableSaveForLater: false,
          removeAction: "/action/cart-item-remove",
          ruleBasedProductLimit: 50,
          showLineItemDescription: false,
          miniCart: {
            enableViewCartButton: true,
          },
        },
        search: {
          placeholder: "Search",
          enableSearchSuggestions: true,
          maxSuggestions: 8,
          enableRecentSearches: true,
          suggestionsDebounce: 400,
        },
        maintenancePage: {
          sharedMaintenancePage: true,
          cdnUrl: "https://prd.cmp.cdn.commercecloud.salesforce.com",
          forwardedHost: "",
        },
      },
      commerce: {
        api: {
          clientId: "",
          organizationId: "",
          shortCode: "",
          proxy: "/mobify/proxy/api",
          callback: "/callback",
          privateKeyEnabled: false,
          registeredRefreshTokenExpirySeconds: undefined,
          guestRefreshTokenExpirySeconds: undefined,
        },
        sites: [
          {
            id: "RefArchGlobal",
            defaultLocale: "en-GB",
            defaultCurrency: "GBP",
            supportedLocales: [
              {
                id: "en-GB",
                preferredCurrency: "GBP",
              },
              {
                id: "da-DK",
                preferredCurrency: "DKK",
              },
              {
                id: "de-DE",
                preferredCurrency: "EUR",
              },
              {
                id: "fi-FI",
                preferredCurrency: "EUR",
              },
              {
                id: "fr-FR",
                preferredCurrency: "EUR",
              },
              {
                id: "it-IT",
                preferredCurrency: "EUR",
              },
              {
                id: "ja-JP",
                preferredCurrency: "JPY",
              },
              {
                id: "ko-KR",
                preferredCurrency: "KRW",
              },
              {
                id: "nl-NL",
                preferredCurrency: "EUR",
              },
              {
                id: "pl-PL",
                preferredCurrency: "PLN",
              },
              {
                id: "sv-SE",
                preferredCurrency: "SEK",
              },
              {
                id: "zh-CN",
                preferredCurrency: "CNY",
              },
              {
                id: "zh-TW",
                preferredCurrency: "TWD",
              },
            ],
            supportedCurrencies: [
              "CNY",
              "DKK",
              "EUR",
              "GBP",
              "JPY",
              "KRW",
              "PLN",
              "SEK",
              "TWD",
            ],
          },
          {
            id: "RefArch",
            defaultLocale: "en-US",
            defaultCurrency: "USD",
            supportedLocales: [
              {
                id: "en-US",
                preferredCurrency: "USD",
              },
            ],
            supportedCurrencies: ["USD"],
          },
        ],
        sitesFromDal: true,
      },
      cookies: { domain: "" },
      defaultSiteId: "RefArch",
      siteAliasMap: {
        RefArch: "us",
        RefArchGlobal: "global",
      },
      hybrid: {
        enabled: false,
        legacyRoutes: [],
      },
      auth: {
        otpLength: 6,
      },
      features: {
        passkey: {
          enabled: false,
          mode: "email",
          callbackUri: "",
        },
        passwordlessLogin: {
          enabled: false,
          mode: "email",
          callbackUri: "/passwordless-login-callback",
          landingUri: "/login",
        },
        otpRequest: {
          mode: "email",
          callbackUri: "",
        },
        resetPassword: {
          mode: "email",
          callbackUri: "/reset-password-callback",
          landingUri: "/reset-password",
        },
        socialLogin: {
          enabled: true,
          callbackUri: "/social-callback",
          providers: ["Apple", "Google"],
        },
        socialShare: {
          enabled: true,
          providers: ["Twitter", "Facebook", "LinkedIn", "Email"],
        },
        guestCheckout: true,
        shopperContext: {
          enabled: true,
        },
        googleCloudAPI: {
          apiKey: "",
        },
        mrtBasedPageDesignerResolution: false,
      },
      i18n: {
        fallbackLng: "en-GB",
        supportedLngs: [
          "da-DK",
          "de-DE",
          "fi-FI",
          "fr-FR",
          "it-IT",
          "ja-JP",
          "ko-KR",
          "nl-NL",
          "pl-PL",
          "sv-SE",
          "zh-CN",
          "zh-TW",
          "en-US",
          "en-GB",
        ],
      },
      global: {
        branding: { name: "Zyne", logoAlt: "Zyne Home" },
        productListing: {
          defaultProductTileImgAspectRatio: 1,
        },
        inventory: { lowStockThreshold: 5 },
        carousel: { defaultItemCount: 4 },
        badges: [
          {
            propertyName: "c_isNew",
            label: "New",
            color: "green",
            priority: 1,
          },
          {
            propertyName: "c_isSale",
            label: "Sale",
            color: "orange",
            priority: 2,
          },
          {
            propertyName: "c_isLimited",
            label: "Limited",
            color: "purple",
            priority: 3,
          },
          {
            propertyName: "c_isExclusive",
            label: "Exclusive",
            color: "blue",
            priority: 4,
          },
          {
            propertyName: "c_isTrending",
            label: "Trending",
            color: "pink",
            priority: 5,
          },
          {
            propertyName: "c_isBestSeller",
            label: "Best Seller",
            color: "yellow",
            priority: 6,
          },
          {
            propertyName: "c_isOutOfStock",
            label: "Out of Stock",
            color: "red",
            priority: 7,
          },
        ],
        skeleton: {
          thumbnails: 4,
          colorVariants: 4,
          sizeVariants: 3,
          accordionSections: 3,
          defaultItemCount: 4,
        },
        recommendations: {
          search_limit: {
            youMightLike: 8,
            completeLook: 12,
            recentlyViewed: 6,
          },
          types: {
            "you-may-also-like": {
              enabled: true,
              priority: 1,
              sort: "best-matches",
              titleKey: "product.recommendations.youMightAlsoLike",
            },
            "complete-the-look": {
              enabled: true,
              priority: 2,
              sort: "price-low-to-high",
              titleKey: "product.recommendations.completeTheLook",
            },
            "recently-viewed": {
              enabled: false,
              priority: 3,
              sort: "most-popular",
              titleKey: "product.recommendations.recentlyViewed",
            },
          },
        },
      },
      links: {
        preconnect: [DIS_DEFAULT_HOST],
      },
      images: {
        quality: 70,
        formats: ["webp"],
        fallbackFormat: "jpg",
        host: DIS_DEFAULT_HOST,
        enableDis: true,
        realmHostMappings: [],
      },
      search: {
        products: {
          refine: {
            orderableOnly: true,
          },
          hits: {
            limit: 24,
            critical: 4,
          },
          images: {
            tile: "medium",
            swatch: "swatch",
          },
        },
      },
      performance: {
        caching: { apiCacheTtl: 300, staticAssetCacheTtl: 31536000 },
        metrics: {
          serverPerformanceMetricsEnabled: false,
          serverTimingHeaderEnabled: false,
          clientPerformanceMetricsEnabled: false,
        },
      },
      engagement: {
        adapters: {
          einstein: {
            enabled: false,
            consentCategory: "analytics",
            host: "https://api.cquotient.com",
            einsteinId: "",
            isProduction: false,
            realm: "",
            siteId: "",
            eventToggles: {
              view_page: true,
              view_product: true,
              view_search: true,
              view_category: true,
              view_recommender: true,
              click_product_in_category: true,
              click_product_in_search: true,
              click_product_in_recommender: true,
              cart_item_add: true,
              checkout_start: true,
              checkout_step: true,
              view_search_suggestion: true,
              click_search_suggestion: true,
              wishlist_item_added: true,
              wishlist_item_removed: true,
              wishlist_viewed: true,
              wishlist_item_merged: true,
              wishlist_merged: true,
            },
          },
          data360: {
            enabled: false,
            consentCategory: "analytics",
            appSourceId: "",
            tenantId: "",
            siteId: "",
            webStoreId: "sfnext",
            eventToggles: {
              view_page: true,
              view_product: true,
              view_search: true,
              view_category: true,
              view_recommender: true,
              click_product_in_category: false,
              click_product_in_search: false,
              click_product_in_recommender: false,
              cart_item_add: false,
              checkout_start: false,
              checkout_step: false,
              view_search_suggestion: false,
              click_search_suggestion: false,
              wishlist_item_added: false,
              wishlist_item_removed: false,
              wishlist_viewed: false,
              wishlist_item_merged: false,
              wishlist_merged: false,
            },
          },
          activeData: {
            enabled: false,
            consentCategory: "analytics",
            host: "",
            siteUUID: "",
            eventToggles: {
              view_page: true,
              view_product: true,
              view_search: true,
              view_category: true,
              view_recommender: false,
              click_product_in_category: false,
              click_product_in_search: false,
              click_product_in_recommender: false,
              cart_item_add: false,
              checkout_start: false,
              checkout_step: false,
              view_search_suggestion: false,
              click_search_suggestion: false,
              wishlist_item_added: false,
              wishlist_item_removed: false,
              wishlist_viewed: false,
              wishlist_item_merged: false,
              wishlist_merged: false,
            },
          },
        },
        analytics: {
          trackingConsent: {
            enabled: true,
            defaultTrackingConsent: TrackingConsent.Declined,
            consentCategories: [
              "necessary",
              "analytics",
              "marketing",
              "personalization",
            ],
            position: "bottom-right",
          },
          pageViewsBlocklist: [
            "/action",
            "/oauth2",
            "/resource",
            "/search",
            "/category",
            "/product",
            "/checkout",
          ],
          pageViewsResetDuration: 1500,
        },
      },
      development: { enableDevtools: true, hotReload: true, strictMode: true },
      cimulateAgent: {
        enabled: false,
        commerceClientScriptSourceUrl: "URL_Redacted",
        scrt2Url:
          "https://orgfarm-a3ef1014a8-dev-ed.develop.my.salesforce-scrt.com",
        salesforceOrgId: "00Dfj00000IxfuR",
        esDeveloperName: "Zyne_Headless_Storefront",
        commerceClientElementId: "cimulate-messaging-container",
        commerceClientDisplayMode: "panel" as const,
      },
      // Free, native alternative to cimulateAgent above — no third-party vendor
      // script required. See src/components/embedded-messaging/README.md.
      embeddedMessaging: {
        enabled: true,
        orgId: "00Dfj00000IxfuR",
        esDeveloperName: "Customer_Support_Service",
        siteUrl:
          "https://orgfarm-a3ef1014a8-dev-ed.develop.my.site.com/ESWCustomerSupportServi1787744978578",
        scrt2Url:
          "https://orgfarm-a3ef1014a8-dev-ed.develop.my.salesforce-scrt.com",
        bootstrapScriptUrl:
          "https://orgfarm-a3ef1014a8-dev-ed.develop.my.site.com/ESWCustomerSupportServi1787744978578/assets/js/bootstrap.min.js",
        language: "en_US",
      },
      extension: generatedExtensionConfig,
      serverExtension: generatedServerExtensionConfig,
      url: {
        prefix: "/:siteId/:localeId",
        excludeRoutes: ["/resource/**", "/action/**"],
      },
      security: {
        turnstile: {
          sites: (() => {
            if (!process.env.PUBLIC__app__security__turnstile__sites) return {};
            try {
              return JSON.parse(
                process.env.PUBLIC__app__security__turnstile__sites,
              );
            } catch {
              console.error(
                "[Turnstile] Failed to parse PUBLIC__app__security__turnstile__sites - no sites configured (fail-closed)",
              );
              return {};
            }
          })(),
          enabled:
            process.env.PUBLIC__app__security__turnstile__enabled === "true",
          mode:
            (process.env.PUBLIC__app__security__turnstile__mode as
              | "managed"
              | "non-interactive"
              | "invisible") || "managed",
          verification: {
            enabled: process.env.TURNSTILE_VERIFICATION_ENABLED === "true",
            mode:
              (process.env
                .PUBLIC__app__security__turnstile__verification__mode as
                | "enforce"
                | "log-only"
                | "disabled") || undefined,
          },
        },
        headers: defaultSecurityHeaders,
      },
    },
  },
  {
    protectedPaths: [
      "app__engagement__adapters__einstein",
      "app__engagement__adapters__data360",
      "app__engagement__adapters__activeData__enabled",
      "app__engagement__adapters__activeData__eventToggles",
      "app__url__prefix",
      "app__url__excludeRoutes",
    ],
  },
);
